### ISSUE TITLE
Looping through shows is slow?

### ISSUE THREAD

**Issue by stevezau** [pkkid/python-plexapi#1188]
### Describe the Bug

Hi, I am looping through shows trying to get the paths. 

```
plex_shows = [m for m in plex.library.section('TV Shows').all()]
plex_shows_by_path = {m.locations[0]: m for m in plex_shows}
```

It is extremely slow. It seems to be querying plex for each item in the location loop. Is there a faster way to do this? I would have thought the data would be pulled from the first line? 

### Operating System and Version

Linux

### Plex Media Server Version

Latest

### Python Version

3.11.2

### PlexAPI Version

Latest

**Comment by JonnyWong16** [comment]
This is expected behaviour. 

The `location` attribute is not available when querying Plex's `/all` endpoint using `all()` and will only return partial objects (you can check with `show.isPartialObject()` or `show.isFullObject()`). Objects are automatically reloaded (see `reload()`) for you when you access a missing attribute which requires querying Plex for the metadata of the individual show.
