### ISSUE TITLE
Support Now Playing Actions

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#132]
There are new options on the Plex >> Status >> Now Playing tab that allow us to stop playback. There may be others as well. Lets get these added.

**Comment by Hellowlol** [comment]
I couldnt find any action.
Ex: https://github.com/JonnyWong16/plexpy/commit/cea851d38ea8dfe432cf7268cc84d8c6fd79cb3d

**Comment by pkkid** [comment]
Terminate a session is the only action I saw. I also just updated my server last night, so maybe its new? It was when I moused over a current session on the status page.

**Comment by Hellowlol** [comment]
Strange, im on 1.4.2.3400 but i cant find this option.

**Comment by shenning00** [comment]
@pkkid - I see the "Stop playback" on the plex.tv site. I don't see it on my 1.4.3.3400 local server. Check for updates doesn't show a new server, but I'm running the Plex Official Docker image. I can check restarting it later to see if it gets an update. 

Also, when I try to "Stop playback" from plex.tv it doesn't stop for the PMP running on my laptop. The Now Playing view shows "error". I'm assuming because the server is not up to date.

**Comment by Hellowlol** [comment]
yeah, i found it now.

**Comment by Hellowlol** [comment]
@pkkid Any reason why players, transcodeSession session (added just now) is a list? Isnt it always just one item?

**Comment by Hellowlol** [comment]
https://github.com/pkkid/python-plexapi/pull/135/commits/cbde4787ccbd54c09ac958fc85d3d6ba26673ff5

**Comment by pkkid** [comment]
@Hellowlol If you had two people playing the same media, would you have two transcodeSessions? If not, then you're right, it shouldn't be a list.

**Comment by pkkid** [comment]
I am seeing the same thing in the UI as shenning00.  THe option shows up on plex.tv, but not my local install. I would guess it's a feature we'll see on the local web client shortly.

**Comment by Hellowlol** [comment]
Hm, I'll test that tomorrow.

**Comment by Hellowlol** [comment]
Yep, I didn't get to to work. It took me forever to understand that they wanted the session if not the transcode id as the old kill option had.
