### ISSUE TITLE
Reloading?

### ISSUE THREAD

**Issue by stevezau** [pkkid/python-plexapi#183]
Hi, I am getting a list of the ep's in Plex via
```
plex_eps = plex.library.section('TV Shows').search(libtype='episode')
```
After that i loop through each of the ep's and read the guid but each time i'm getting

```
[08/Sep/2017 15:07:10] WARNING [plexapi:283] Reloading Episode 'Episode 28' for attr 'guid'
```

It's extremely slow, can i prevent the reloading? I should guid would of populated on the first query?

**Comment by Hellowlol** [comment]
Using the currect master branch i dont have any issues regarding reloading. But its a slow anyway, but i dont know how we can speed it up. 

The issue is that plex it self is really slow.
Using http://10.0.0.97:32400/library/all?type=4&X-Plex-Token=xxxxx <- get all episodes in my entire library takes 1.4 minutes just to get the http response.
Because some responses is really slow we try to request less data from plex a the time.  (see https://github.com/pkkid/python-plexapi/blob/master/plexapi/__init__.py#L19) but even if i patch this its slow. :(

**Comment by stevezau** [comment]
Hmmm weird, i'm using master and for me it reloads the show..

The below 
```
for show in plex.library.section('TV Shows').search(libtype='show'):
    tvdb_match = re.search(r'thetvdb://([0-9]+)', show.guid)
```

Triggers 

```[08/Sep/2017 21:51:24] WARNING [plexapi:283] Reloading Show 'xxxxxxxxxxx' for attr 'guid'```

**Comment by pkkid** [comment]
The reloading needs to happen because guid is not specified in the listing from the search() call. When you try to access the variable show.guid we see that it's missing and do a full reload of the show.

You should see a first URL called similar to the following.  If you load that URL up in chrome you should be able to see the XML response and see that guid is in fact missing.
2017-09-08 08:11:58,300       server:338  DEBUG     GET http://<PLEXURL>:32400/library/sections/2/all?type=2&X-Plex-Container-Size=50&X-Plex-Container-Start=0&X-Plex-Token=<TOKEN>

**Comment by stevezau** [comment]
Ah, how annoying!
