### ISSUE TITLE
Support smart playlist

### ISSUE THREAD

**Issue by Hellowlol** [pkkid/python-plexapi#221]
post 

https://ip:32400/playlists?type=video&title=TV%20Shows&smart=1&uri=library%3A%2F%2Fc6aaf29c-85a2-40dc-9a42-71ebcd615c9f%2Fdirectory%2F%252Flibrary%252Fsections%252F2%252Fall%253Ftype%253D4%2526episode.viewCount%25253E%25253E%253D0%2526sourceType%253D4&X-Plex-Product=Plex%20Web&X-Plex-Version=3.20.7&X-Plex-Client-Identifier=fzzf&X-Plex-Platform=Chrome&X-Plex-Platform-Version=61.0&X-Plex-Device=Windows&X-Plex-Device-Name=Plex%20Web%20%28Chrome%29&X-Plex-Device-Screen-Resolution=1280x615%2C1280x720&X-Plex-Token=xxx

**Comment by Hellowlol** [comment]
@pkkid Any idea what travis is complaining about in my branch? https://github.com/pkkid/python-plexapi/tree/smart

**Comment by pkkid** [comment]
I noticed sometimes things fail and if I kick it off again it will pass. I just started you're one failing build again, we can see if this is the case. -- We should figure it out and be a bit ore graceful, but I never put time into it yet.

**Comment by blacktwin** [comment]
Some of the FILTERS or sectionChoices are not working properly when attempting to create a Smart Playlist.

`plex.createPlaylist("test", section="Movies", smart=True, unwatched=True, **{'genre':"Horror"})`
This will not user the unwatched FILTER/Choice, instead you just get the genre filter. Also because `title` is used for the naming of the Playlist `**{'title':'Die Hard'}` will return: `TypeError: create() got multiple values for argument 'title'`.  Maybe changing the parameter to `name` or `playlist_title`?

As it happens, looks like I accidentally omitted `title` from the `ALLOWED_FILTERS` for the MovieSection in PR #364 .

**Comment by blacktwin** [comment]
PR incoming for `playlist.py`

```python
        for category, value in kwargs.items():
            if section.listChoices(category):
                sectionChoices = section.listChoices(category)
                for choice in sectionChoices:
                    if str(choice.title).lower() == str(value).lower():
                        uri = uri + '&%s=%s' % (category.lower(), str(choice.key))
            ####New check for BOOLEN FILTER
            if category in section.BOOLEAN_FILTERS:
                int_bool = section._cleanSearchFilter(category, value)
                uri = uri + '&%s=%s' % (category.lower(), str(int_bool))
```
previous code would not pass `unwatched` filter if used.
`plex.createPlaylist("test", section="Movies", smart=True, unwatched=True, **{'genre':"Horror"})` or 
`plex.createPlaylist("test", section="Movies", smart=True, **{'unwatched':True, 'genre':"Horror"})`

Any thoughts on what to rename the `title` parameter? `playlist_title` or `playlistTtile`
