### ISSUE TITLE
recentlyAdded() returns only season, not episode

### ISSUE THREAD

**Issue by Brawl345** [pkkid/python-plexapi#264]
When I add an episode for a series and use `library.recentlyAdded()`, I only get the season, not the new episode. Using `library.LibrarySection.recentlyAdded()` returns the episode correctly however, but this is inconvenient because I would like to get all new media from all libraries. Not sure if this is a bug or an API restriction?

**Comment by Hellowlol** [comment]
So loop the sections and add them to a list?

**Comment by Brawl345** [comment]
That's only a workaround of the issue? And if I want to check for new media I have to save every last media in every library seperately instead of having one endpoint. Sure I can do that, but that seems rather "meh".

**Comment by Hellowlol** [comment]
I don’t think there is a another way. I think is stacked by default. You don’t need to store anything.. you add only the new stuff to the list. It’s literally 3 lines of code.

**Comment by Brawl345** [comment]
Yeah I know, my end goal is a bot for Telegram which sends info for recently added media as soon as it's uploaded, that's why I said I need to store it. If it itsn't possible then no problem, was just wondering.

**Comment by pkkid** [comment]
The items returned in the result set for `library.recentlyAdded()` and `library.LibrarySection.recentlyAdded()` are just returning to you what the Plex server itself returns to us. Changing what Plex gives us for convenience is not really part of the mission of this project.

Since you have a workaround and there is not really an action for us to take, I'm going to close this one.
