### ISSUE TITLE
Cannot Connect To PMS With Self Signed SSL

### ISSUE THREAD

**Issue by barrycarey** [pkkid/python-plexapi#295]
If PMS has Secure Connections set to Required plexapi fails to connect if SSL is self signed. 

There's no way to pass verify=False to requests avoid this error. 

An option would be to pass verify=False to the PlexServer constructor and then kwards to query.

**Comment by Hellowlol** [comment]
Use your own session object.

**Comment by Hellowlol** [comment]
```
import requests
from plexapi.server import PlexServer

session = requests.Session()
session.verify = False

pms = PlexServer(url, token, session=session)


```

**Comment by luigi311** [comment]
Looks like this is no longer working. When i use this method it will give me a warning and still connect but when i actually try use the connection i get this error
[ERROR]: Plex: Failed to get watched, Error: HTTPSConnectionPool(host='IP', port=32400): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'IP' doesn't match '*.91b33fc9fb6a44f09838dda19de3ab45.plex.direct'")))
