### ISSUE TITLE
Family and Friends settings exposed

### ISSUE THREAD

**Issue by MichaelFay** [pkkid/python-plexapi#350]
It would be very useful if there was the ability to create/delete a home user.

**Comment by MichaelFay** [comment]
The parameters will need to change to something like this: 

```python
params = {
            'server_id': machineId,
            'shared_server': {'library_section_ids': sectionIds, **'title'**: username},
            'sharing_settings': {
                'allowSync': ('1' if allowSync else '0'),
                'allowCameraUpload': ('1' if allowCameraUpload else '0'),
                'allowChannels': ('1' if allowChannels else '0'),
                'filterMovies': self._filterDictToStr(filterMovies or {}),
                'filterTelevision': self._filterDictToStr(filterTelevision or {}),
                'filterMusic': self._filterDictToStr(filterMusic or {}),
            },
        }

```

**Comment by blacktwin** [comment]
Have you tried out this code? Do you intend to create a PR? 

Looks like its a copy and paste of the `inviteFriend()` function with the exception to the `invited_email` to `title`. 

I think the `FRIENDINVITE` url would be incorrect. The url should be `plex.tv/api/home/users?title={title}` not `'plex.tv/api/servers/{machineId}/shared_servers'` although when creating a home user that url is posted as well but with `invited_id` instead of `invited_id`. So it looks like there would be need for additional code to be added.

**Comment by MichaelFay** [comment]
@blacktwin I can definitely pull the project and test that functionality then create a pr. I won't be able to get to it for a little bit as some stuff has come up.

**Comment by blacktwin** [comment]
@Hellowlol @pkkid I believe this can now be closed.
