### ISSUE TITLE
Editing userRating of a track does not save

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [pkkid/python-plexapi#354]
When using track.edit(userRating=x), the PUT request that is sent uses userRating= as shown by this non-working PUT from my server logs:

Jun 24, 2019 16:59:02.860 [0x7fdab37fe700] DEBUG - Completed: [192.168.7.23:5647
0] 200 PUT /library/sections/3/all?type=10&userRating=0.0&id=8037 (7 live) GZIP 
3ms 195 bytes (pipelined: 5)

Changing the userRating via the web UI results in:

Jun 24, 2019 16:56:35.082 [0x7fdab37fe700] DEBUG - Completed: [192.168.7.21:5247
4] 200 PUT /library/sections/3/all?type=10&id=8037&includeExternalMedia=1&userRa
ting.value=2 (6 live) TLS GZIP 36ms 274 bytes (pipelined: 1)

I have worked around this by including

```
        if 'userRating' in kwargs:
            kwargs['userRating.value'] = kwargs['userRating']
            del kwargs['userRating']
```

In PlexPartialObject.edit() locally, but it feels really hacky, and I'm wondering if the other float values for tracks require the same handling. I'd be delighted to push up a PR with some direction.

**Comment by pkkid** [comment]
Nice find, this does seem like a change in behavior, or maybe an oversight because there was no test. I'm fine with the change mentioned as long as it's commented well. Just editing the General section of a movie shows the following, so I suspect all rating related fields may have this quirk. 
```
type=1
&id=13781
&includeExternalMedia=1
&rating.value=4.6
&rating.locked=1
...
```

I'd hate to require this off field naming when using the API. Perhaps rather than hard coding each individual field with an if statement, we have a mapping at the top of the file.  Something like the following:

```python
EDIT_MAPPING = {
    'rating': 'rating.value',
    'userRating': 'userRating.value',
    ...
}

# In the function the code may look something like:
for key, value in kwargs.items():
    if key in EDIT_MAPPING:
       kwargs[key] = kwargs.pop(EDIT_MAPPING[key])
```

**Comment by Hellowlol** [comment]
It doesn’t work because you not using it correctly. It you look up the docs is clearly shows that the user has to handle everything them selves. This is intended as the edit can pretty much be using to edit everything from a library to a movie.

I don’t think we should accept any other behavior then the current one. Ideally we should be able to change the properties and use save as we do with settings. But I’m not sure it’s worth it as it would bloat every media type we have.

**Comment by s-t-e-v-e-n-k** [comment]
Having to construct a dict and pass it into edit using ** seems equally hacky to me. :-)

I'm going to see if what @pkkid suggested can be expressed succinctly. With a test!

**Comment by Hellowlol** [comment]
1. It’s not a oversight
2. It’s is a test for edit
3. It’s documented 

Imo we shouldn’t touch edit in base. If we really need to it should be done in the classes (like we do for playlist)

**Comment by s-t-e-v-e-n-k** [comment]
Where is it documented? I can't see anything about some attributes requiring to be passed as '<attribute>.value' into edit()? Also, I can see one test for edit for a library as a whole, but not for a specific item.

**Comment by Hellowlol** [comment]
It’s in the example of the docs string. It show that you need to handle everything your self. As for the edit is used in the test for edit library and add label remove label genre etc

**Comment by pkkid** [comment]
Thanks @Hellowlol, sorry I missed the docs too.

**Comment by blacktwin** [comment]
There may be a large variety of different tags and suffix tags. Running the action or a similar action within the WebUI and capturing/viewing the query/payload would be how you'd determine what is needed for each action. The `*.value` tag seems quiet common so maybe added that to the docstring or an example using that tag would be helpful.

**Comment by JonnyWong16** [comment]
Objects have a `rate()` method for user ratings now.

https://python-plexapi.readthedocs.io/en/stable/modules/mixins.html#plexapi.mixins.RatingMixin.rate
