### ISSUE TITLE
Accessing some attributes can wipe valid objects

### ISSUE THREAD

**Issue by jjlawren** [pkkid/python-plexapi#397]
It seems that sometimes when accessing certain attributes, it can "reset" the parent object.

I found that when accessing the `session` attribute on one of the `plexserver.sessions()` objects, it would occasionally clear the whole parent. The Plex server sometimes doesn't include the `Session` key in the XML when calling `/status/sessions`, and it's wiped out by this magic: 
https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L277-L291 

Here's an example to reproduce: https://gist.github.com/jjlawren/abbde9585ff25bece264ab3fc7dc8dbc

During the second iteration, it will wipe out all of the useful data _if_ the `Sessions` key is missing.

I don't know if other attributes can cause this to happen.

**Comment by pkkid** [comment]
Do you have any clues what might may cause the session key to be missing? -- I ran the two for loops on my machine with a playing tvshow and movie and am getting expected results; but the sessions key is not missing for me.

**Comment by jjlawren** [comment]
No, it's not readily reproducible, but I've definitely seen it when playing music most often. 

I've encountered the issue when playing an album, played a movie instead, and then went back to the same music track and the missing `Session` key appeared to clear itself up. The same Plex client was used through all those steps.

**Comment by pkkid** [comment]
I'm able to force the bug to happen. -- When we see None or empty list, we assume the object returned from Plex is incomplete and reload the official full object from the url defined by `self.key`.  The problem here is that new object doesn't store any information about the playing sessions of that object, and they get overwritten with the empty data in `Playable()`.

A few small choices in code changes I can think of to help you get by this and still maintain reloading objects for the more common scenarios:
1. We add a specific check in  __getattribute__ similar to [line 281](https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L281) specifically to skip reload for the 'session' attribute.
2. We can add a class variable DONT_RELOAD_FOR_KEYS = ['key', 'session'] to the PlexPartialObject class, and use that. This would be OK because it makes it somewhat configurable the next time we hit it.
3. We don't overwrite values on any objects that are missing in the reloaded object. -- I think this option is a very large code change, and needs to be thought out a lot more. In some cases updating a class variable to None for missing information may actually be the correct thing to do.

I like option #2 above because the change is minimal and the use case seems small.

**Comment by pkkid** [comment]
Try replacing the top section of `PlexPartialObject` with the following..

```python
class PlexPartialObject(PlexObject):
    """ Not all objects in the Plex listings return the complete list of elements
        for the object. This object will allow you to assume each object is complete,
        and if the specified value you request is None it will fetch the full object
        automatically and update itself.
    """
    DONT_RELOAD_FOR_KEYS = ['key', 'session']

    def __eq__(self, other):
        return other is not None and self.key == other.key

    def __hash__(self):
        return hash(repr(self))

    def __iter__(self):
        yield self

    def __getattribute__(self, attr):
        # Dragons inside.. :-/
        value = super(PlexPartialObject, self).__getattribute__(attr)
        # Check a few cases where we dont want to reload
        if attr in self.DONT_RELOAD_FOR_KEYS: return value
        if attr.startswith('_'): return value
        if value not in (None, []): return value
        if self.isFullObject(): return value
        # Log the reload.
        clsname = self.__class__.__name__
        title = self.__dict__.get('title', self.__dict__.get('name'))
        objname = "%s '%s'" % (clsname, title) if title else clsname
        log.debug("Reloading %s for attr '%s'" % (objname, attr))
        # Reload and return the value
        self.reload()
        return super(PlexPartialObject, self).__getattribute__(attr)
```

**Comment by pkkid** [comment]
If the above works for you, let me know and I'll get it committed.

**Comment by jjlawren** [comment]
Thanks! I'll test the next time I encounter the issue.

**Comment by jjlawren** [comment]
@pkkid btw, did you have to manufacture the issue or did you find a reliable way to reproduce? I'm trying to understand the conditions where this normally occurs.

**Comment by Hellowlol** [comment]
It can only happen when accessing attributes that we don’t have access to when the object is built. Atm that only session and players as this info is only available at status/sessions endpoint. 

When plexapi tries to reload info it uses the another endpoint to grab missing attributes (because it’s the most comple one) this intended because if we prefetched this we would use one http call for each episode, movie regardless you you needed that attribute or not.

To recreate this issue you can feed the xml to data manually to elementre and use server.findItems to make the object manually  see https://github.com/pkkid/python-plexapi/blob/master/plexapi/base.py#L148 for a example. 

Just try to use the full xml. Delete the session tag and/or players and try to access players and session attribute and you will see that this reloads the object and makes players and session “blank”

I can make a example script later cba with doing that on mobile.

**Comment by pkkid** [comment]
@jjlawren I manufactured the issue.

**Comment by jjlawren** [comment]
Ran into the behavior again today and was able to reproduce. Putting your diff into place prevented the object from being wiped out. Looks good!
