### ISSUE TITLE
Commands only run after initial setup

### ISSUE THREAD

**Issue by DutchyOven** [pkkid/python-plexapi#516]
**Describe the issue**
When I run Python3 on my RPi4 then run the below command

```
from plexapi.server import PlexServer
baseurl = 'http://192.168.1.2:32400'
token = 'XXXXXXXXXXXXXXXXXXXXXXXX'
plex = PlexServer(baseurl, token)
```

I can then run the example

```
# Example 2: Mark all Game of Thrones episodes watched.
plex.library.section('TV Shows').get('Game of Thrones').markWatched()
```

It works fine, marks it as watched. Now if I leave Python and go back in and try to run that command it won't run. it'll say 

```
>>> plex.library.section('TV Shows').get('Game of Thrones').markWatched()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'plex' is not defined
```

but again if I enter From plexapi.... piece of code I can run it again.

Am I supposed to tell it to use plexapi somehow? Is there some kind of command I need to use when starting my RPi4 to start up plexapi? 

I'm new at this so is there something I'm doing wrong? I did the normal install pip3 install plexapi, then I do the from plexapi... then I run the command but as soon as I try to get python to run that same command again it doesn't know what I'm talking about. 

**Expected behavior**
I want it to be able to run commands without having to enter that from plexapi.server

**Enviroment (please complete the following information):**
 - OS: [Raspbian Buster]
 - Python Version [3.7]
 - PlexAPI version [latest]

**Additional context**
Add any other context about the issue here.

**Comment by blacktwin** [comment]
Thats not how it works. Your issue seems to stem from not understanding how python works. Which like you say, you're new so no foul. But addressing that issue is outside the scope of this project and you'll need to educate yourself.

I'm assuming that you're opening up your terminal and typing `python` to start an interactive python session. This interactive shell is temporary and meant for quick single line coding. Once you `exit()` from the session it's dumped from memory. If you want to retain the information and imports of libraries you'll want to use an IDE or text editor to create a run a `script.py` file. Type out your base  structure of imports and variable assignments and edit and run your `script.py` using `python ./path/to/script.py`. If you're looking for examples of using PlexAPI and scripting please check out my [JBOPS (Just a Bunch of Plex Scripts)](https://github.com/blacktwin/JBOPS) repo.

**Comment by DutchyOven** [comment]
> 
> 
> Thats not how it works. Your issue seems to stem from not understanding how python works. 


Ha, yep! I've only used it on windows and I would edit .py or other scripts and they'd run fine.

The thing is my .py script doesn't run either.

I have a file called markaswatched.py with this inside

```
# Example 2: Mark all Game of Thrones episodes watched.
plex.library.section('TV Shows').get('Insecure').markWatched()
```

I then go to ssh and do cd home/plexapi_scripts

then I enter python3 markaswatched.py and it does the same thing


```
michael@pivpn:~/docker/plexapi_scripts $ python3 markaswatched.py
Traceback (most recent call last):
  File "markaswatched.py", line 2, in <module>
    plex.library.section('TV Shows').get('Insecure').markWatched()
NameError: name 'plex' is not defined
```

I did the same with python instead of python3 and same, obviously since I installed it with python3. 

BTW thanks again twin, this is puptentjoe from reddit lol. I just wanted to start as simple as possible and then move on to your more complicated ones.

**Comment by jjlawren** [comment]
You'll need to make sure the "setup" code is included in each script you run:
```
from plexapi.server import PlexServer
baseurl = 'http://192.168.1.2:32400'
token = 'XXXXXXXXXXXXXXXXXXXXXXXX'
plex = PlexServer(baseurl, token)
```
This creates the `plex` object you're calling here:
```
plex.library.section('TV Shows').get('Insecure').markWatched()
```
Without the setup, `plex` does not exist and you cannot call `.library` on it.

**Comment by DutchyOven** [comment]
> 
> 
> You'll need to make sure the "setup" code is included in each script you run:

Well that makes sense! It worked, thank you!
