### ISSUE TITLE
AttributeError: 'Show' object has no attribute 'grandparentTitle'

### ISSUE THREAD

**Issue by josopu** [pkkid/python-plexapi#728]
**Describe the issue**

When searching for a show, it breaks

**Code snippets**

```shell
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/scripts/000_self/telegram_recently_added.py", line 447, in <module>
            code = show(p)
        File "/scripts/000_self/telegram_recently_added.py", line 212, in show
            if parser.show_name == episode.grandparentTitle and datetime_threshold < episode.addedAt and str(episode.seasonNumber) in season_nums:
        File "/app/tautulli/lib/plexapi/base.py", line 428, in __getattribute__
            value = super(PlexPartialObject, self).__getattribute__(attr)
    AttributeError: 'Show' object has no attribute 'grandparentTitle'
```

**Expected behavior**

To retrieve the Show

**Enviroment (please complete the following information):**

 - OS: Docker on unraid
 - Plex version 1.22.2.4282
 - Python Version 3.7.8
 - PlexAPI version 4.5.2

**Comment by Hellowlol** [comment]
I don’t see any errors here except from the traceback. You have called some of this episode but plexapi reports this as a show.

Can you share your script?

**Comment by josopu** [comment]
It seems that it was a tautulli problem, which was sending a show when only new episode was added (or something similar). This issue may be closed, sorry

**Comment by JonnyWong16** [comment]
That should be expected because `library.recentlyAdded()` should be the "Date Added" option in Plex Web which is common between all library types.

![image](https://user-images.githubusercontent.com/9099342/118407594-4a8a5100-b636-11eb-8d7e-37fa5341466e.png)

What is missing is an option for "Last Episode Date Added" which should be a new method such as `tvshows.recentlyAddedEpisodes()`. Please open a new bug report for this. In the meantime, you can get the same results using `tvshows.search(sort='episode.addedAt:desc', libtype='episode', maxresults=50)`
