### ISSUE TITLE
Un-neccessary reload called for legacy agent on guids

### ISSUE THREAD

**Issue by glensc** [pkkid/python-plexapi#807]
**Describe the issue**

When trying to access `guids` attribute on a media item that's in Legacy Movie Agent the code internally tries to reload the item, which always returns empty and thus resulting useless roundtrip to server.

**Code snippets**

The input XML is something like:

```xml
<Video ratingKey="8057" key="/library/metadata/8057" guid="com.plexapp.agents.imdb://ttXXXXXX?lang=en"
```

It does not have `guids` XML attribute at all.

**Expected behavior**

Optimize, that for legacy agent, guids resolve round-trip won't be performed but return `[]` immediately.

**Enviroment (please complete the following information):**

 - Plex version: 1.23.3.4707-ebb5fe9f3
 - Python Version: 3.9
 - PlexAPI version: 4.7.0

**Additional context**

- https://github.com/pkkid/python-plexapi/blob/4.7.0/plexapi/base.py#L463
- https://github.com/Taxel/PlexTraktSync/pull/401#issuecomment-890468775
- https://github.com/Taxel/PlexTraktSync/pull/406

**Comment by Hellowlol** [comment]
Why ask for attribute that you know dont exist?

**Comment by glensc** [comment]
portable code. I wouldn't know if it exists, knowing it would mean to detect is the library behind the legacy agent or not.

**Comment by JonnyWong16** [comment]
This is competely expected behavior and a core feature of `plexapi`. The legacy agents will be removed from Plex at some point, so all development on `plexapi` is focussed on all the new agents. All of our CI tests are run against the new agents. 

You can add `guids` to `USER_DONT_RELOAD_FOR_KEYS` and perform your own check for the legacy/new agents to decide when to reload manually.
