### ISSUE TITLE
ANSI Escape Sequences

### ISSUE THREAD

**Issue by Andr3-Jardim** [pkkid/python-plexapi#886]
### Describe the Bug

Printing ANSI escape sequences does not produce the expected output.
![image_2022-02-12_193921](https://user-images.githubusercontent.com/68620319/153725852-ff634f2a-3656-4a9b-be54-194aecec8904.png)

### Code Snippets

```python
print('Before import: \033[38;5;196mred\033[0;0m')

from plexapi.myplex import MyPlexAccount

print('After import: \033[38;5;196mred\033[0;0m')
```

### Operating System and Version

Windows 11

### Plex Media Server Version

1.40.1.2823

### Python Version

3.8.0

### PlexAPI Version

4.9.2

**Comment by JonnyWong16** [comment]
This isn't really due to PlexAPI. It's the `tqdm` library.

https://github.com/tqdm/tqdm/issues/678

```py
print('Before import: \033[38;5;196mred\033[0;0m')

import tqdm

print('After import: \033[38;5;196mred\033[0;0m')
```

PlexAPI only uses `tqdm` to show a progress bar if you use the Plex download function from the command line. You can safely remove this library from your computer if you don't need it, or create a virtual environment without `tqdm`.

**Comment by Andr3-Jardim** [comment]
I should have checked the dependency tree. Thank you!
